<?php

use phpDocumentor\Reflection\Types\This;

$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepalidatepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basepath('js/search.js'))
    ->appendFile($this->basepath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basepath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basepath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'))
    ->appendFile($this->basepath('js/Leavemanagement/LeaveReport/index.js'));

?>
<style>
    .table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #e3e3e3 !important;
}
 .table th {
    padding: 0.75rem;
    border-top: 1px solid #e3e3e3;
    background-color:#f1f4f7;
    box-shadow: #ccc;
    text-align: center;
    font-size: 1.5rem !important;
    font-weight: 600 !important;
}
</style>
<script>
    document.searchValues =<?php echo json_encode($searchValues) ?>;
    document.acl =<?php echo json_encode($acl); ?>;
    document.preference =<?php echo json_encode($preference) ?>;
    document.pullLeaveReportListLink='<?=$this->url("leaveReport",["action"=>"pullLeaveReportList"])?>';
    document.getLeaveYearMonthLink = '<?php echo $this->url("leaveReport", ['action' => 'getLeaveYearMonth']); ?>';
</script>


<div class="page-bar">
    <?=$this->navigation('Zend\Navigation\leaveReport')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb')?>
</div>
<?php 
if ($this->message && (sizeof($this->messages)>1)){
    print 'div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismissable="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>

<?php if ($this->messages){?>
    <script>
        document.message=<?php  echo json_encode($this->messages);?>
    </script>
<?php } ?>

<div class="portlet light bg-inverse">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-paper-plane font-green-haze"></i>
            <span class="caption-subject bold font-green-haze uppercase">Search</span>
        </div>
        <div class="tools">
            <a href="" class="collapse" data-original-title="" title=""></a>
            <a href="" class="fullscreen" data-original-title="" title=""></a>

        </div>
        <div class="actions">
        <div class="btn-group">
        <a href="javascript:;" class="btn btn-sm blue-soft" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-copy"></i>Tools
            <i class="fa fa-angle-down"></i>
        </a>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="javascript:;" id="excelExport">
                    <i class="fa fa-file-excel-o"></i>
                    Export to Excel
                </a>
            </li>
            <li>
                <a href="javascript:;" id="pdfExport">
                    <i class="fa fa-file-pdf-o"></i>
                    Export to PDF
                </a>
            </li>
        </ul>
    </div>
  </div>
 </div>
<div class="portlet-body">
    <div class="row">
        <div class="col-sm-2">
            <label>Year</label> <br>
            <select  id="leaveYear"></select>
        </div>
       <div class="col-sm-2">
        <label>Month</label> <br>
        <select id="leaveMonth"></select>
       </div>
        <div class="col-sm-2 " >
            <label>Company</label>
            <select multiple class="form-control" name="company" id="companyId">
            </select>
        </div>
        <div class="col-sm-2" style="margin-left:79rem;">
            <button id="search" class="btn tbn-default btn-sm pull-right">
                Search
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
  </div>
</div>
<div class="leaveReportTable" id="leaveReportTable">
    <!-- <table class="table">
        <thead class="thead-dark">
            <tr style="height:50px ;" >
                <th class="thead" >Function</th>
                <th class="thead">Head Count</th>
                <th class="thead">Earned Leave</th>
                <th class="thead">Actual Leave Used</th>
                <th class="thead">Used Leave %</th>
            </tr>
            <?php
                // while($rows=$result->fetch_assoc())
                // {
                // ?>
                // }
                // <tr>
                //     <td><?php echo $recordList['']?></td>
                // </tr>
            <?php
                // }
            ?>
        </thead>

    </table> -->
</div>
